### ISSUE TITLE
Management commands to create CSVs for static data

### ISSUE THREAD

**Issue by jirmauritz** [adaptive-learning/flocs#184]
- tasks, concepts, instructions, blocks
- sync names of columns with attepmt.log and instances.log

**Comment by effa** [comment]
Concerning names of columns, I think it's best to have them in snake_case (e.g `concept_id`), because when read by Pandas, the columns can then be accessed directly (e.g. `df.concept_id`). It also allows for the rows to be specified by namedtuples, where the column names corresponds to field names, which are again Python identifiers, see e.g. https://github.com/adaptive-learning/flocs/blob/master/concepts/models/concept.py where the export tuple is specified and https://github.com/adaptive-learning/flocs/blob/master/flocs/management/commands/export_data_to_csv.py where its field names are used as column names of a CSV file.

**Comment by effa** [comment]
Done. You can now use `make export-data-to-csv ` to create exports of all static data (and in near future probably of all data for analysis).
